FROM openjdk
WORKDIR usr/lib
ADD ./target/monthly-tracker-service-0.0.1-SNAPSHOT.jar /usr/lib/monthly-tracker-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "monthly-tracker-service-0.0.1-SNAPSHOT.jar"]